### ISSUE TITLE
No NSP

### ISSUE THREAD

**Issue by MikeAtom** [nkrapivin/RussellNX#1]
idk what's wrong, cause i have proper runtime and _08 keys, but when the program finishes building, it opens an empty folder
![изображение](https://user-images.githubusercontent.com/42153279/71766042-3f80c600-2f04-11ea-82eb-30d6726b4879.png)

![изображение](https://user-images.githubusercontent.com/42153279/71766046-4c9db500-2f04-11ea-9852-9c18e7fa6f32.png)

**Comment by nkrapivin** [comment]
ah, I know what's wrong, folder "Switch Programs" has a space and hacBrewPack thinks "-k blablablaSwitch" and " Programs" are two different arguments and thus it can't load the keyset file.

**Comment by nkrapivin** [comment]
Will be fixed in 1.1.1
I'll just surround path to keys.txt using ""
so it'll be -k "D:\bla\можно ведь и по русски писать\MikeAtom\гы"
also lowering KeyGeneration.
Issue closed.
