### ISSUE TITLE
"&&" rule problem

### ISSUE THREAD

**Issue by xBitsoft** [nkrapivin/RussellNX#2]
I'm getting a lot of errors while my game is running due to problems with the way RussellNX compiles the switch code. I do not get this problem with Windows or with previous non-RussellNX switch builds of my game. The problem and an example:

The code:
`if my_parent != -1 && my_parent.var123 = 2 {}`

How it executes on Windows and previous non-RussellNX switch builds:
_if **my_parent is not equal to -1** ---> proceed to check if my_parent.var123 = 2_
OR:
_if **my_parent is equal to -1** ---> do **not** proceed to check my_parent.var123 thus skipping the rest of the expression since the first test is false_

How it executes on RussellNX switch builds:
_regardless of my_parent meeting the expression test ---> proceed to check if my_parent.var123 = 2_

I'm not sure how to better describe the problem but I hope the description is adequate and can be resolved.

Thank you for your work on this project.

**Comment by nkrapivin** [comment]
I guess it's not a problem with RussellNX but with GMAssetCompiler itself.

Are you sure this *only* happens when using RussellNX?

**Comment by nkrapivin** [comment]
okay turns out I was lied to, and I disabled Short Circuting, please try with 1.2.2.

**Comment by xBitsoft** [comment]
It's fixed in 1.2.2.
Thanks so much!
