### ISSUE TITLE
Need GMS2 runtime 2.2.3.344

### ISSUE THREAD

**Issue by NBAPJ** [nkrapivin/RussellNX#5]
Hi I been trying to use RussellNX but I can't find the runtime needed to run the program.  It's not available for download on GameMaker website anymore and I can't install it through the program.  I also downloaded the zip file but it's not installing. I was wondering if you could provide me with runtime I need to use your program.  Right now when I click on the exe nothing happens.  I have tried v1.38 and 1.40.  When I tried v1.0 it said the runtime wasn't installed.   Thanks

**Comment by nkrapivin** [comment]
Fixed in v1.5.2
