### ISSUE TITLE
Any chance we get a new build with runtime 2.3.2.426?

### ISSUE THREAD

**Issue by felipezacani** [nkrapivin/RussellNX#7]
Just like the title says, any chance we get a new build with runtime 2.3.2.426?

I could also help with this if I had more details on how to build and package it (the runtime).

Thanks!

**Comment by nkrapivin** [comment]
Hello.

Can you please manually update your installation to v1.5.0?
By manually updating I mean, remove every single file except for RussellNX.ini and copy everything from the 1.5.0 archive.

The new RussellNX version comes with a pre-built latest 2.3.2 runtime.

**Comment by felipezacani** [comment]
Огромное спасибо

I hope that really means thanks! :)

There is a little bug I was able to fix but I think its not worth the fork/pull request effort, maybe you can fix and publish it a lot faster?

I had to add 
`Directory.CreateDirectory(iconsDir);`
after line 340 in MainForm.cs, the "control" dir doesn't exist during the build process and this generates an exception.

**Comment by nkrapivin** [comment]
> Огромное спасибо
> 
> I hope that really means thanks! :)
> 
> There is a little bug I was able to fix but I think its not worth the fork/pull request effort, maybe you can fix and publish it a lot faster?
> 
> I had to add
> `Directory.CreateDirectory(iconsDir);`
> after line 340 in MainForm.cs, the "control" dir doesn't exist during the build process and this generates an exception.
> 
> After this little fix, it worked perfectly!

huh, weird, okay I'll add this fix later.

**Comment by nkrapivin** [comment]
Fixed in v1.5.2
