### ISSUE TITLE
Could we get a NRO option sometime soon?

### ISSUE THREAD

**Issue by Artsmen** [nkrapivin/RussellNX#9]
I am completely new to switch hacking and I just recently ported a game to switch with this program, But there was an issue I had, It exports as NSP! I know that's how it's intended and that's fine but my main issue is just that custom NSP files have a ban risk and I just wanted to ask if a NRO export option would be possible in the future build atleast. If it isn't I'll still stick to NSP files but I just wanted to know in advance

**Comment by nkrapivin** [comment]
No. If you mean `hbmenu` NROs, they're a different format, they do not rely on any SDKs unlike GameMaker.
GameMaker is a commercial licensed game engine.
You're probably looking for something like LovePotion (a Lua game framework) if you want to make NRO games.
